services:
  zenthicAlpha.api:
    image: ${DOCKER_REGISTRY-}zenthic_alpha
    container_name: zenthicAlpha.api
    build:
      secrets:
        - identity_connection_string
        - oauth_google_client_id
        - oauth_google_client_secret
      context: .
      dockerfile: source/ZenthicAlpha/Dockerfile
    depends_on:
      - zenthicAlpha.database
      - zenthicAlpha.cache

  zenthicAlpha.database:
    image: mcr.microsoft.com/mssql/server
    container_name: zenthicAlpha.database
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: Password123!
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
    volumes:
      - ./orchestration/docker/mssql/data:/var/opt/mssql/data

  zenthicAlpha.cache:
    image: redis
    container_name: zenthicAlpha.cache
    ports:
      - 6379:6379
    restart: always

  zenthicAlpha.smtp:
    image: mailhog/mailhog
    container_name: zenthicAlpha.smtp
    ports:
      - 8025:8025
      - 1025:1025

  zenthicAlpha.logger:
    image: datalust/seq
    container_name: zenthicAlpha.logger
    ports:
      - 5341:80
    environment:
      ACCEPT_EULA: Y
    volumes:
      - ./orchestration/docker/seq/data:/data
    restart: unless-stopped

secrets:
  identity_connection_string:
    environment: ConnectionStrings__IdentityModuleDbContext
  oauth_google_client_id:
    environment: AuthSettings__OAuth__Google__ClientId
  oauth_google_client_secret:
    environment: AuthSettings__OAuth__Google__ClientSecret