services:
  zenthicAlpha.api:
    image: ${DOCKER_REGISTRY-}presentation
    container_name: zenthicAlpha.api
    build:
      context: .
      dockerfile: Presentation/Dockerfile

  zenthicAlpha.database:
    image: mcr.microsoft.com/mssql/server
    container_name: zenthicAlpha.database
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Password123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
    volumes:
      - ./Database:/var/opt/mssql/data

  zenthicAlpha.cache:
    image: redis
    container_name: zenthicAlpha.cache
    ports:
      - 6379:6379
    restart: always

  zenthicAlpha.smtp:
    image: mailhog/mailhog
    container_name: zenthicAlpha.smtp
    ports:
      - 8025:8025
      - 1025:1025